<?php
/** @var \MediaLounge\Slider\Block\Slider $block */
$configs = $block->getSliderConfigs();
?>
<?php if ($block->getSlides()): ?>
<div>
	<div class="slick-slider <?php echo $block->getSliderUniqueId(); ?>">
		<?php foreach ($block->getSlides() as $slide): ?>
			<div class="item"><?php echo $block->getCmsFilterContent($slide->getContent()); ?></div>
		<?php endforeach; ?>
	</div>
</div>
    <script>
        require([
            'jquery',
            'slick'
        ], function () {
            jQuery(document).ready(function () {
                jQuery(".slick-slider.<?php echo $block->escapeJs($block->getSliderUniqueId()); ?>").slick({
                    dots: false,
                    arrows: false,
                    pagination: false,
                    infinite: true,
                    autoplay: true,
                    fade: <?php echo $block->escapeJs($configs['fade']); ?>,
                    autoplaySpeed: <?php echo $block->escapeJs($configs['autoplaySpeed']); ?>,
                    pauseOnHover: <?php echo $block->escapeJs($configs['pauseOnHover']); ?>,
                    cssEase: '<?php echo $block->escapeJs($configs['cssEase']); ?>',
                });
            });
        });
    </script>
<?php endif;?>